# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c56be4413d6502deb03a4a49d3e996cea9abf496dc0ecc09b9bfa7ebb9d6e0a9bda54e76d8f0fc37b7aff91173cd9063c642e2f6d47e587aaaa4aa3d61fbf15f

test:
  secret_key_base: afe0b95a234704386075d415fb52ec590edabdc85c8dc3b56bac0df598ac64b1ae571e2652b8ad968bf5aa309d4bbad6b70c78fb5aae4e63a090ce7b0221c583

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
